# ПНППК/ui/config/relay_config.yaml
# Configuration for the Relay device
Relay:
  baudrate: 115200 # Baud rate for communication
  slave_id: 6 # MODBUS slave ID for the Relay
  timeout: 10 # Response timeout in milliseconds
  data_bits: 8 # Count of data bits
  stop_bits: 1 # Count of stop bits

# Note: Data bits (8) and stop bits (1) are fixed by the API defaults.
